condition_set_id: condition_set_count

conditioning_db: conditioning.db

condition_generator:
  count_prompts:
    base_count: 400
    include_numeral_variant: true
    include_background_variant: true
    object_indices: [39, 40, 41, 42, 43, 44, 45]
    backgrounds: ["unicolor background", "white background", "plain background"]
    number_range: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
