experiment_id: experiment_003

# Optional overrides (default to metrics.db and analytics.db under OUTPUT_DIRECTORY)
metrics_db: metrics.db
analytics_db: analytics.db

# Which analyses to run
analyses:
  count_analysis: true
  numeral_vs_text: true
  background_effect: true
  model_hierarchy: true
  pixel_confidence: true
  suspicious_bboxes: true
